# Generated by Django 3.0.2 on 2020-02-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
