# Generated by Django 3.0.2 on 2020-02-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ForeignKey(choices=[((), ())], on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
        ),
    ]
