# Generated by Django 3.0.2 on 2020-02-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
