# Generated by Django 3.0.2 on 2020-02-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200212_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogImage',
            field=models.ImageField(null=True, upload_to='blog_pictures'),
        ),
    ]
